// ==UserScript==
// @name         DO Face Generator
// @namespace    http://tampermonkey.net/
// @version      v1.0
// @description  Players Face Pictures Generated Via AI
// @author       Jurubatuba FC (Luis Scalise)
// @match        https://www.dugout-online.com/players/details/youth/*
// @grant        GM_openInTab
// @grant        unsafeWindow
// @grant        GM_xmlhttpRequest
// @grant        GM_addStyle
// @downloadURL  https://github.com/jurubatubafc/do-face-generator/blob/main/facegenerator.user.js
// @updateURL    https://github.com/jurubatubafc/do-face-generator/blob/main/facegenerator.user.js
// ==/UserScript==

(async function() {
    'use strict';

    // Common functions session
    // Function to remove non-numeric characters
    function removeNonNumeric(inputString) {
        return inputString.replace(/\D/g, '');
    }

    // Function to return correlation of players positions and countries in English
    function ToEnglish(origin, correlation) {
        for (var i = 0; i < correlation.length; i++) {
            if (correlation[i][0] === origin) {
                return correlation[i][1];
            }
        }
        return origin;
    }

    // Function to map base age to range age
    function mapToAgeRange(baseAge) {
        if (baseAge >= 13 && baseAge <= 18) {
            return '13';
        } else if (baseAge >= 19 && baseAge <= 29) {
            return '19';
        } else if (baseAge >= 30 && baseAge <= 40) {
            return '30';
        } else {
            return '30';
        }
    }

    // Extracts Age of the Player
    var targetAgeNPos = 'https://www.dugout-online.com/images/flags_small/new/';
    var dynamicAge = $('tbody tr:has(img[src^="' + targetAgeNPos + '"])')
        .next() // Move to the next tr (second tr)
        .find('td:last-child') // Find the last td within the second tr
        .text();

    // Extracts Country of the Player
    var targetCountry = 'https://www.dugout-online.com/images/flags_round/half/';
    var divCountryImg = $('div:has(img[src^="' + targetCountry + '"])');

    // Extracts Player's Position
    var dynamicPos = $('tbody tr:has(img[src^="' + targetAgeNPos + '"])')
        .next() // Move to the second tr
        .next() // Move to the third tr
        .find('td:last-child') // Find the last td within the third tr
        .text();

    // Array of players position correlations
    var positionCorrelation = [
        ["Portero", "Goalkeeper"],
        ["Defensor", "Defender"],
        ["Centrocampista", "Midfielder"],
        ["Delantero", "Forward"],
        ["Portiere", "Goalkeeper"],
        ["Difensore", "Defender"],
        ["Attaccante", "Forward"],
        ["Doelman", "Goalkeeper"],
        ["Verdediger", "Defender"],
        ["Middenvelder", "Midfielder"],
        ["Aanvaller", "Forward"],
        ["Goleiro", "Goalkeeper"],
        ["Meio-campista", "Midfielder"],
        ["Atacante", "Forward"],
        ["Portar", "Goalkeeper"],
        ["Fundaș", "Defender"],
        ["Mijlocaș", "Midfielder"],
        ["Atacant", "Forward"],
        ["Vratar", "Goalkeeper"],
        ["Branilec", "Defender"],
        ["Vezist", "Midfielder"],
        ["Napadalec", "Forward"],
        ["Kaleci", "Goalkeeper"],
        ["Defans", "Defender"],
        ["Orta saha", "Midfielder"],
        ["Forvet", "Forward"],
        ["골키퍼", "Goalkeeper"],
        ["수비수", "Defender"],
        ["미드필더", "Midfielder"],
        ["공격수", "Forward"]
    ];

    // Array of countries correlations
    var countryCorrelation = [
        ["Južna Afrika", "South Africa"],
        ["Albanija", "Albania"],
        ["Njemačka", "Germany"],
        ["Alžir", "Algeria"],
        ["Argentina", "Argentina"],
        ["Australija", "Australia"],
        ["Austrija", "Austria"],
        ["Bangladeš", "Bangladesh"],
        ["Belgija", "Belgium"],
        ["Bolivija", "Bolivia"],
        ["Bosna i Hercegovina", "Bosnia and Herzegovina"],
        ["Brazil", "Brazil"],
        ["Bugarska", "Bulgaria"],
        ["Kanada", "Canada"],
        ["Čile", "Chile"],
        ["Kina", "China"],
        ["Kolumbija", "Colombia"],
        ["Južna Koreja", "South Korea"],
        ["Hrvatska", "Croatia"],
        ["Danska", "Denmark"],
        ["Škotska", "Scotland"],
        ["Slovačka", "Slovakia"],
        ["Slovenija", "Slovenia"],
        ["Španjolska", "Spain"],
        ["Sjedinjene Američke Države", "United States"],
        ["Estonija", "Estonia"],
        ["Finska", "Finland"],
        ["Francuska", "France"],
        ["Grčka", "Greece"],
        ["Nizozemska", "Netherlands"],
        ["Mađarska", "Hungary"],
        ["Indija", "India"],
        ["Engleska", "England"],
        ["Irska", "Ireland"],
        ["Island", "Iceland"],
        ["Izrael", "Israel"],
        ["Italija", "Italy"],
        ["Japan", "Japan"],
        ["Latvija", "Latvia"],
        ["Litva", "Lithuania"],
        ["Malta", "Malta"],
        ["Meksiko", "Mexico"],
        ["Moldavija", "Moldova"],
        ["Norveška", "Norway"],
        ["Novi Zeland", "New Zealand"],
        ["Peru", "Peru"],
        ["Poljska", "Poland"],
        ["Portugal", "Portugal"],
        ["Crna Gora", "Montenegro"],
        ["Češka", "Czech Republic"],
        ["Rumunjska", "Romania"],
        ["Rusija", "Russia"],
        ["Srbija", "Serbia"],
        ["Švedska", "Sweden"],
        ["Švicarska", "Switzerland"],
        ["Tajland", "Thailand"],
        ["Turska", "Turkey"],
        ["Urugvaj", "Uruguay"],
        ["Venezuela", "Venezuela"],
        ["Sudáfrica", "South Africa"],
        ["Albania", "Albania"],
        ["Alemania", "Germany"],
        ["Argelia", "Algeria"],
        ["Argentina", "Argentina"],
        ["Australia", "Australia"],
        ["Austria", "Austria"],
        ["Bangladesh", "Bangladesh"],
        ["Bélgica", "Belgium"],
        ["Bolivia", "Bolivia"],
        ["Bosnia y Herzegovina", "Bosnia and Herzegovina"],
        ["Brasil", "Brazil"],
        ["Bulgaria", "Bulgaria"],
        ["Canadá", "Canada"],
        ["Chile", "Chile"],
        ["China", "China"],
        ["Colombia", "Colombia"],
        ["Corea del Sur", "South Korea"],
        ["Croacia", "Croatia"],
        ["Dinamarca", "Denmark"],
        ["Escocia", "Scotland"],
        ["Eslovaquia", "Slovakia"],
        ["Eslovenia", "Slovenia"],
        ["España", "Spain"],
        ["Estados Unidos", "United States"],
        ["Estonia", "Estonia"],
        ["Finlandia", "Finland"],
        ["Francia", "France"],
        ["Grecia", "Greece"],
        ["Países Bajos", "Netherlands"],
        ["Hungría", "Hungary"],
        ["India", "India"],
        ["Inglaterra", "England"],
        ["Irlanda", "Ireland"],
        ["Islandia", "Iceland"],
        ["Israel", "Israel"],
        ["Italia", "Italy"],
        ["Japón", "Japan"],
        ["Letonia", "Latvia"],
        ["Lituania", "Lithuania"],
        ["Malta", "Malta"],
        ["México", "Mexico"],
        ["Moldavia", "Moldova"],
        ["Noruega", "Norway"],
        ["Nueva Zelanda", "New Zealand"],
        ["Perú", "Peru"],
        ["Polonia", "Poland"],
        ["Portugal", "Portugal"],
        ["Montenegro", "Montenegro"],
        ["República Checa", "Czech Republic"],
        ["Rumania", "Romania"],
        ["Rusia", "Russia"],
        ["Serbia", "Serbia"],
        ["Suecia", "Sweden"],
        ["Suiza", "Switzerland"],
        ["Tailandia", "Thailand"],
        ["Turquía", "Turkey"],
        ["Uruguay", "Uruguay"],
        ["Venezuela", "Venezuela"],
        ["Sudafrica", "South Africa"],
        ["Albania", "Albania"],
        ["Germania", "Germany"],
        ["Algeria", "Algeria"],
        ["Argentina", "Argentina"],
        ["Australia", "Australia"],
        ["Austria", "Austria"],
        ["Bangladesh", "Bangladesh"],
        ["Belgio", "Belgium"],
        ["Bolivia", "Bolivia"],
        ["Bosnia ed Erzegovina", "Bosnia and Herzegovina"],
        ["Brasile", "Brazil"],
        ["Bulgaria", "Bulgaria"],
        ["Canada", "Canada"],
        ["Cile", "Chile"],
        ["Cina", "China"],
        ["Colombia", "Colombia"],
        ["Corea del Sud", "South Korea"],
        ["Croazia", "Croatia"],
        ["Danimarca", "Denmark"],
        ["Scozia", "Scotland"],
        ["Slovacchia", "Slovakia"],
        ["Slovenia", "Slovenia"],
        ["Spagna", "Spain"],
        ["Stati Uniti", "United States"],
        ["Estonia", "Estonia"],
        ["Finlandia", "Finland"],
        ["Francia", "France"],
        ["Grecia", "Greece"],
        ["Paesi Bassi", "Netherlands"],
        ["Ungheria", "Hungary"],
        ["India", "India"],
        ["Inghilterra", "England"],
        ["Irlanda", "Ireland"],
        ["Islanda", "Iceland"],
        ["Israele", "Israel"],
        ["Italia", "Italy"],
        ["Giappone", "Japan"],
        ["Lettonia", "Latvia"],
        ["Lituania", "Lithuania"],
        ["Malta", "Malta"],
        ["Messico", "Mexico"],
        ["Moldavia", "Moldova"],
        ["Norvegia", "Norway"],
        ["Nuova Zelanda", "New Zealand"],
        ["Perù", "Peru"],
        ["Polonia", "Poland"],
        ["Portogallo", "Portugal"],
        ["Montenegro", "Montenegro"],
        ["Repubblica Ceca", "Czech Republic"],
        ["Romania", "Romania"],
        ["Russia", "Russia"],
        ["Serbia", "Serbia"],
        ["Svezia", "Sweden"],
        ["Svizzera", "Switzerland"],
        ["Thailandia", "Thailand"],
        ["Turchia", "Turkey"],
        ["Uruguay", "Uruguay"],
        ["Venezuela", "Venezuela"],
        ["Zuid-Afrika", "South Africa"],
        ["Albanië", "Albania"],
        ["Duitsland", "Germany"],
        ["Algerije", "Algeria"],
        ["Argentinië", "Argentina"],
        ["Australië", "Australia"],
        ["Oostenrijk", "Austria"],
        ["Bangladesh", "Bangladesh"],
        ["België", "Belgium"],
        ["Bolivia", "Bolivia"],
        ["Bosnië en Herzegovina", "Bosnia and Herzegovina"],
        ["Brazilië", "Brazil"],
        ["Bulgarije", "Bulgaria"],
        ["Canada", "Canada"],
        ["Chili", "Chile"],
        ["China", "China"],
        ["Colombia", "Colombia"],
        ["Zuid-Korea", "South Korea"],
        ["Kroatië", "Croatia"],
        ["Denemarken", "Denmark"],
        ["Schotland", "Scotland"],
        ["Slowakije", "Slovakia"],
        ["Slovenië", "Slovenia"],
        ["Spanje", "Spain"],
        ["Verenigde Staten", "United States"],
        ["Estland", "Estonia"],
        ["Finland", "Finland"],
        ["Frankrijk", "France"],
        ["Griekenland", "Greece"],
        ["Nederland", "Netherlands"],
        ["Hongarije", "Hungary"],
        ["India", "India"],
        ["Engeland", "England"],
        ["Ierland", "Ireland"],
        ["IJsland", "Iceland"],
        ["Israël", "Israel"],
        ["Italië", "Italy"],
        ["Japan", "Japan"],
        ["Letland", "Latvia"],
        ["Litouwen", "Lithuania"],
        ["Malta", "Malta"],
        ["Mexico", "Mexico"],
        ["Moldavië", "Moldova"],
        ["Noorwegen", "Norway"],
        ["Nieuw-Zeeland", "New Zealand"],
        ["Peru", "Peru"],
        ["Polen", "Poland"],
        ["Portugal", "Portugal"],
        ["Montenegro", "Montenegro"],
        ["Tsjechië", "Czech Republic"],
        ["Roemenië", "Romania"],
        ["Rusland", "Russia"],
        ["Servië", "Serbia"],
        ["Zweden", "Sweden"],
        ["Zwitserland", "Switzerland"],
        ["Thailand", "Thailand"],
        ["Turkije", "Turkey"],
        ["Uruguay", "Uruguay"],
        ["Venezuela", "Venezuela"],
        ["África do Sul", "South Africa"],
        ["Albânia", "Albania"],
        ["Alemanha", "Germany"],
        ["Argélia", "Algeria"],
        ["Argentina", "Argentina"],
        ["Austrália", "Australia"],
        ["Áustria", "Austria"],
        ["Bangladesh", "Bangladesh"],
        ["Bélgica", "Belgium"],
        ["Bolívia", "Bolivia"],
        ["Bósnia e Herzegovina", "Bosnia and Herzegovina"],
        ["Brasil", "Brazil"],
        ["Bulgária", "Bulgaria"],
        ["Canadá", "Canada"],
        ["Chile", "Chile"],
        ["China", "China"],
        ["Colômbia", "Colombia"],
        ["Coréia do Sul", "South Korea"],
        ["Croácia", "Croatia"],
        ["Dinamarca", "Denmark"],
        ["Escócia", "Scotland"],
        ["Eslováquia", "Slovakia"],
        ["Eslovênia", "Slovenia"],
        ["Espanha", "Spain"],
        ["Estados Unidos", "United States"],
        ["Estônia", "Estonia"],
        ["Finlândia", "Finland"],
        ["França", "France"],
        ["Grécia", "Greece"],
        ["Holanda", "Netherlands"],
        ["Hungria", "Hungary"],
        ["Índia", "India"],
        ["Inglaterra", "England"],
        ["Irlanda", "Ireland"],
        ["Islândia", "Iceland"],
        ["Israel", "Israel"],
        ["Itália", "Italy"],
        ["Japão", "Japan"],
        ["Letônia", "Latvia"],
        ["Lituânia", "Lithuania"],
        ["Malta", "Malta"],
        ["México", "Mexico"],
        ["Moldávia", "Moldova"],
        ["Noruega", "Norway"],
        ["Nova Zelândia", "New Zealand"],
        ["Peru", "Peru"],
        ["Polônia", "Poland"],
        ["Portugal", "Portugal"],
        ["Rep. de Montenegro", "Montenegro"],
        ["República Checa", "Czech Republic"],
        ["Romênia", "Romania"],
        ["Rússia", "Russia"],
        ["Sérvia", "Serbia"],
        ["Suécia", "Sweden"],
        ["Suíça", "Switzerland"],
        ["Tailândia", "Thailand"],
        ["Turquia", "Turkey"],
        ["Uruguai", "Uruguay"],
        ["Venezuela", "Venezuela"],
        ["Africa de Sud", "South Africa"],
        ["Albania", "Albania"],
        ["Germania", "Germany"],
        ["Algeria", "Algeria"],
        ["Argentina", "Argentina"],
        ["Australia", "Australia"],
        ["Austria", "Austria"],
        ["Bangladesh", "Bangladesh"],
        ["Belgia", "Belgium"],
        ["Bolivia", "Bolivia"],
        ["Bosnia și Herțegovina", "Bosnia and Herzegovina"],
        ["Brazilia", "Brazil"],
        ["Bulgaria", "Bulgaria"],
        ["Canada", "Canada"],
        ["Chile", "Chile"],
        ["China", "China"],
        ["Columbia", "Colombia"],
        ["Coreea de Sud", "South Korea"],
        ["Croația", "Croatia"],
        ["Danemarca", "Denmark"],
        ["Scoția", "Scotland"],
        ["Slovacia", "Slovakia"],
        ["Slovenia", "Slovenia"],
        ["Spania", "Spain"],
        ["Statele Unite", "United States"],
        ["Estonia", "Estonia"],
        ["Finlanda", "Finland"],
        ["Franța", "France"],
        ["Grecia", "Greece"],
        ["Țările de Jos", "Netherlands"],
        ["Ungaria", "Hungary"],
        ["India", "India"],
        ["Anglia", "England"],
        ["Irlanda", "Ireland"],
        ["Islanda", "Iceland"],
        ["Israel", "Israel"],
        ["Italia", "Italy"],
        ["Japonia", "Japan"],
        ["Letonia", "Latvia"],
        ["Lituania", "Lithuania"],
        ["Malta", "Malta"],
        ["Mexic", "Mexico"],
        ["Moldova", "Moldova"],
        ["Norvegia", "Norway"],
        ["Noua Zeelandă", "New Zealand"],
        ["Peru", "Peru"],
        ["Polonia", "Poland"],
        ["Portugalia", "Portugal"],
        ["Muntenegru", "Montenegro"],
        ["Cehia", "Czech Republic"],
        ["România", "Romania"],
        ["Rusia", "Russia"],
        ["Serbia", "Serbia"],
        ["Suedia", "Sweden"],
        ["Elveția", "Switzerland"],
        ["Thailanda", "Thailand"],
        ["Turcia", "Turkey"],
        ["Uruguay", "Uruguay"],
        ["Venezuela", "Venezuela"],
        ["Južna Afrika", "South Africa"],
        ["Albanija", "Albania"],
        ["Nemčija", "Germany"],
        ["Alžirija", "Algeria"],
        ["Argentina", "Argentina"],
        ["Avstralija", "Australia"],
        ["Avstrija", "Austria"],
        ["Bangladeš", "Bangladesh"],
        ["Belgija", "Belgium"],
        ["Bolivija", "Bolivia"],
        ["Bosna in Hercegovina", "Bosnia and Herzegovina"],
        ["Brazilija", "Brazil"],
        ["Bolgarija", "Bulgaria"],
        ["Kanada", "Canada"],
        ["Čile", "Chile"],
        ["Kitajska", "China"],
        ["Kolumbija", "Colombia"],
        ["Južna Koreja", "South Korea"],
        ["Hrvaška", "Croatia"],
        ["Danska", "Denmark"],
        ["Škotska", "Scotland"],
        ["Slovaška", "Slovakia"],
        ["Slovenija", "Slovenia"],
        ["Španija", "Spain"],
        ["Združene države Amerike", "United States"],
        ["Estonija", "Estonia"],
        ["Finska", "Finland"],
        ["Francija", "France"],
        ["Grčija", "Greece"],
        ["Nizozemska", "Netherlands"],
        ["Madžarska", "Hungary"],
        ["Indija", "India"],
        ["Anglija", "England"],
        ["Irska", "Ireland"],
        ["Islandija", "Iceland"],
        ["Izrael", "Israel"],
        ["Italija", "Italy"],
        ["Japonska", "Japan"],
        ["Latvija", "Latvia"],
        ["Litva", "Lithuania"],
        ["Malta", "Malta"],
        ["Mehika", "Mexico"],
        ["Moldavija", "Moldova"],
        ["Norveška", "Norway"],
        ["Nova Zelandija", "New Zealand"],
        ["Peru", "Peru"],
        ["Poljska", "Poland"],
        ["Portugalska", "Portugal"],
        ["Črna gora", "Montenegro"],
        ["Češka", "Czech Republic"],
        ["Romunija", "Romania"],
        ["Rusija", "Russia"],
        ["Srbija", "Serbia"],
        ["Švedska", "Sweden"],
        ["Švica", "Switzerland"],
        ["Tajska", "Thailand"],
        ["Turčija", "Turkey"],
        ["Urugvaj", "Uruguay"],
        ["Venezuela", "Venezuela"],
        ["Güney Afrika", "South Africa"],
        ["Arnavutluk", "Albania"],
        ["Almanya", "Germany"],
        ["Cezayir", "Algeria"],
        ["Arjantin", "Argentina"],
        ["Avustralya", "Australia"],
        ["Avusturya", "Austria"],
        ["Bangladeş", "Bangladesh"],
        ["Belçika", "Belgium"],
        ["Bolivya", "Bolivia"],
        ["Bosna-Hersek", "Bosnia and Herzegovina"],
        ["Brezilya", "Brazil"],
        ["Bulgaristan", "Bulgaria"],
        ["Kanada", "Canada"],
        ["Şili", "Chile"],
        ["Çin", "China"],
        ["Kolombiya", "Colombia"],
        ["Güney Kore", "South Korea"],
        ["Hırvatistan", "Croatia"],
        ["Danimarka", "Denmark"],
        ["İskoçya", "Scotland"],
        ["Slovakya", "Slovakia"],
        ["Slovenya", "Slovenia"],
        ["İspanya", "Spain"],
        ["Amerika Birleşik Devletleri", "United States"],
        ["Estonya", "Estonia"],
        ["Finlandiya", "Finland"],
        ["Fransa", "France"],
        ["Yunanistan", "Greece"],
        ["Hollanda", "Netherlands"],
        ["Macaristan", "Hungary"],
        ["Hindistan", "India"],
        ["İngiltere", "England"],
        ["İrlanda", "Ireland"],
        ["İzlanda", "Iceland"],
        ["İsrail", "Israel"],
        ["İtalya", "Italy"],
        ["Japonya", "Japan"],
        ["Letonya", "Latvia"],
        ["Litvanya", "Lithuania"],
        ["Malta", "Malta"],
        ["Meksika", "Mexico"],
        ["Moldova", "Moldova"],
        ["Norveç", "Norway"],
        ["Yeni Zelanda", "New Zealand"],
        ["Peru", "Peru"],
        ["Polonya", "Poland"],
        ["Portekiz", "Portugal"],
        ["Karadağ", "Montenegro"],
        ["Çek Cumhuriyeti", "Czech Republic"],
        ["Romanya", "Romania"],
        ["Rusya", "Russia"],
        ["Sırbistan", "Serbia"],
        ["İsveç", "Sweden"],
        ["İsviçre", "Switzerland"],
        ["Tayland", "Thailand"],
        ["Türkiye", "Turkey"],
        ["Uruguay", "Uruguay"],
        ["Venezuela", "Venezuela"],
        ["남아프리카", "South Africa"],
        ["알바니아", "Albania"],
        ["독일", "Germany"],
        ["알제리", "Algeria"],
        ["아르헨티나", "Argentina"],
        ["호주", "Australia"],
        ["오스트리아", "Austria"],
        ["방글라데시", "Bangladesh"],
        ["벨기에", "Belgium"],
        ["볼리비아", "Bolivia"],
        ["보스니아 헤르체고비나", "Bosnia and Herzegovina"],
        ["브라질", "Brazil"],
        ["불가리아", "Bulgaria"],
        ["캐나다", "Canada"],
        ["칠레", "Chile"],
        ["중국", "China"],
        ["콜롬비아", "Colombia"],
        ["대한민국", "South Korea"],
        ["크로아티아", "Croatia"],
        ["덴마크", "Denmark"],
        ["스코틀랜드", "Scotland"],
        ["슬로바키아", "Slovakia"],
        ["슬로베니아", "Slovenia"],
        ["스페인", "Spain"],
        ["미국", "United States"],
        ["에스토니아", "Estonia"],
        ["핀란드", "Finland"],
        ["프랑스", "France"],
        ["그리스", "Greece"],
        ["네덜란드", "Netherlands"],
        ["헝가리", "Hungary"],
        ["인도", "India"],
        ["영국", "England"],
        ["아일랜드", "Ireland"],
        ["아이슬란드", "Iceland"],
        ["이스라엘", "Israel"],
        ["이탈리아", "Italy"],
        ["일본", "Japan"],
        ["라트비아", "Latvia"],
        ["리투아니아", "Lithuania"],
        ["몰타", "Malta"],
        ["멕시코", "Mexico"],
        ["몰도바", "Moldova"],
        ["노르웨이", "Norway"],
        ["뉴질랜드", "New Zealand"],
        ["페루", "Peru"],
        ["폴란드", "Poland"],
        ["포르투갈", "Portugal"],
        ["몬테네그로", "Montenegro"],
        ["체코", "Czech Republic"],
        ["루마니아", "Romania"],
        ["러시아", "Russia"],
        ["세르비아", "Serbia"],
        ["스웨덴", "Sweden"],
        ["스위스", "Switzerland"],
        ["태국", "Thailand"],
        ["터키", "Turkey"],
        ["우루과이", "Uruguay"],
        ["베네수엘라", "Venezuela"]
    ];

    // Select the image element based on the provided src attribute and replace it for the one wanted
    var imgElement = document.querySelector('img[src="https://www.dugout-online.com/images/club/profile/player-pic-default.png"]');
    imgElement.style.zIndex = '1';

    if (imgElement) {
        // Replace the image source with the desired URL and create consts
        const generatedFace = document.createElement('img');
        imgElement.style.position = 'absolute';
        imgElement.style.left = '0';
        const paddingTopValue = '8px';
        const paddingLeftValue = '13px';
        generatedFace.src = 'https://github.com/jurubatubafc/do-face-generator/blob/main/face-db/'+ mapToAgeRange(removeNonNumeric(dynamicAge)) + '-' + ToEnglish(divCountryImg.find('img').attr('title'), countryCorrelation) + '-' + ToEnglish(dynamicPos, positionCorrelation) +'.jpg?raw=true';

        // Set the position, width and height of the image - also sets up the default message to get behind the new image
        generatedFace.style.position = 'absolute';
        generatedFace.style.paddingTop = paddingTopValue;
        generatedFace.style.paddingLeft = paddingLeftValue;
        generatedFace.width = 122;
        generatedFace.height = 122;
        generatedFace.style.zIndex = '2';
        generatedFace.style.left = '0';
        imgElement.parentNode.appendChild(generatedFace);
    }

})();
